let numero = parseInt (prompt( 'Digite um número para a tabuada das operações:'))
//parseInt faz a conversão da string digitada pelo usuário em number

console.log( numero + 1 )
console.log( numero + 2 )
console.log( numero + 3 )
console.log( numero + 4 )
console.log( numero + 5 )
console.log( numero + 6 )
console.log( numero + 7 )
console.log( numero + 8 )
console.log( numero + 9 )
console.log( numero + 10)

console.log( numero - 1 )
console.log( numero - 2 )
console.log( numero - 3 )
console.log( numero - 4 )
console.log( numero - 5 )
console.log( numero - 6 )
console.log( numero - 7 )
console.log( numero - 8 )
console.log( numero - 9 )
console.log( numero - 10)

console.log( numero * 1 )
console.log( numero * 2 )
console.log( numero * 3 )
console.log( numero * 4 )
console.log( numero * 5 )
console.log( numero * 6 )
console.log( numero * 7 )
console.log( numero * 8 )
console.log( numero * 9 )
console.log( numero * 10)

console.log( numero / 1 )
console.log( numero / 2 )
console.log( numero / 3 )
console.log( numero / 4 )
console.log( numero / 5 )
console.log( numero / 6 )
console.log( numero / 7 )
console.log( numero / 8 )
console.log( numero / 9 )
console.log( numero / 10)




